# Generated by Django 2.1 on 2021-12-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekognize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
